export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Testimonials } from './Testimonials'
export { default as CTA } from './CTA'
export { default as ContactForm } from './ContactForm'
